sudo: required
services:
  - docker

before_install:
  - docker build -t gilsonfagundes/docker-react -f Dockerfile.dev .

script:
  - docker run gilsonfagundes/docker-react npm run test -- --coverage

language: generic   