sudo: required
services:
  - docker

script:
  - docker build t- gilsonfagundes/docker-react -f Dockerfile.dev .
  - docker run gilsonfagundes/docker-react npm run test -- --coverage

language: generic   