sudo: required
services:
  - docker

before_install:
  - docker build -t gilsonfagundes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gilsonfagundes/docker-react npm run test -- --coverage

 deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-516287327302"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY